//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinnerDish
    {
        public string UNID { get; set; }
        public string Name { get; set; }
        public string ShopId { get; set; }
        public string CategoryId { get; set; }
        public int Sort { get; set; }
        public decimal Price { get; set; }
        public string Label { get; set; }
        public string Image { get; set; }
        public int State { get; set; }
        public string Description { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
