//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsOrder
    {
        public string UNID { get; set; }
        public string GoodsId { get; set; }
        public string OpenId { get; set; }
        public string PersonId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> AllPrice { get; set; }
        public Nullable<int> ScoreNum { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
