//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Menu")]
    public partial class Menu
    {
        public string UNID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Sort { get; set; }
        public Nullable<long> LimitFlag { get; set; }
        public string Link { get; set; }
        public string ParentID { get; set; }
        public string ClassName { get; set; }
        public long Flag { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
