//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string UNID { get; set; }
        public Nullable<long> RoleFlag { get; set; }
        public string Account { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public long Flag { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string TargetID { get; set; }
        public Nullable<int> TargetCode { get; set; }
    }
}
