//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public string UNID { get; set; }
        public Nullable<int> TargetCode { get; set; }
        public string TargetID { get; set; }
        public string OnePrize { get; set; }
        public Nullable<int> OnePrizeCount { get; set; }
        public string TwoPrize { get; set; }
        public Nullable<int> TwoPrizeCount { get; set; }
        public string ThreePrize { get; set; }
        public Nullable<int> ThreePrizeCount { get; set; }
        public Nullable<int> AllCount { get; set; }
        public Nullable<int> ExpectedPeopleCount { get; set; }
        public Nullable<int> DayLimt { get; set; }
        public Nullable<int> AllCountLimt { get; set; }
        public Nullable<bool> IsShowCount { get; set; }
        public Nullable<long> Flag { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    }
}
