//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public string UNID { get; set; }
        public int TargetCode { get; set; }
        public string TargetID { get; set; }
        public string OnePrize { get; set; }
        public int OnePrizeCount { get; set; }
        public string OnePrizeImage { get; set; }
        public string TwoPrize { get; set; }
        public int TwoPrizeCount { get; set; }
        public string TwoPrizeImage { get; set; }
        public string ThreePrize { get; set; }
        public int ThreePrizeCount { get; set; }
        public string ThreePrizeImage { get; set; }
        public int AllCount { get; set; }
        public int ExpectedPeopleCount { get; set; }
        public int hadPrizeCount { get; set; }
        public int DayLimt { get; set; }
        public int AllCountLimt { get; set; }
        public int IsShowCount { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
