//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScratchCard
    {
        public string UNID { get; set; }
        public string Name { get; set; }
        public string KeyWord { get; set; }
        public string RepeatNotice { get; set; }
        public string PreheatingTitle { get; set; }
        public string PreheatingImage { get; set; }
        public string PreheatingDescribe { get; set; }
        public string OngoingTitle { get; set; }
        public string OngoingImage { get; set; }
        public string OngoingDescribe { get; set; }
        public string OverTitle { get; set; }
        public string OverImage { get; set; }
        public string OverDescribe { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<long> Flag { get; set; }
    }
}
