//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string OpenID { get; set; }
        public string NickName { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
