//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserJoinCounter
    {
        public string UNID { get; set; }
        public int TargetCode { get; set; }
        public string TargetID { get; set; }
        public string OpenID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int IsPrize { get; set; }
        public int PrizeGrade { get; set; }
        public string SN { get; set; }
        public int IsCach { get; set; }
        public Nullable<System.DateTime> CachTime { get; set; }
    }
}
