//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wall
    {
        public string UNID { get; set; }
        public string AppId { get; set; }
        public string Name { get; set; }
        public string Sponsor { get; set; }
        public string SponsorLogo { get; set; }
        public string TopLogo { get; set; }
        public string Qrcode { get; set; }
        public string BackgroundImage { get; set; }
        public System.DateTime OngoingTime { get; set; }
        public System.DateTime OverTime { get; set; }
        public string Describe { get; set; }
        public string TipLogo { get; set; }
        public int IsShowVedio { get; set; }
        public string Vedio { get; set; }
        public int IsOpen { get; set; }
        public int IsAudting { get; set; }
        public int IsShow { get; set; }
        public Nullable<long> ContentFlag { get; set; }
        public Nullable<long> Flag { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
